name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        uses: actions-ecosystem/action-get-latest-tag@v1
        run: echo"${{ steps.release-label.outputs.level != null }}"