name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        run: | 
            release= $(curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/silence-laboratories/silent-shard-dkls23-ll/releases/latest")
            echo "$release" 
            echo "lalal"
            B="A"
            echo "$B"
#             tag=echo "$release" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

