name: Continuous Integration

on:
  push:
    branches:
      - main

#  pull_request:
#    branches:
#      - main
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: echo "${{  github.event.release.name }}"