name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: version
        run: | 
            release=$(curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/silence-laboratories/silent-shard-dkls23-ll/releases/latest")
            tag=$(echo "$release" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
            tag=$(echo "$tag" | cut -c 2-)
            echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: build npm packages
        run: |
          curl --proto '=https' --tlsv1.2 -sySf https://sh.rustup.rs | sh
          rustup target add wasm32-unknown-unknown
          cargo install wasm-opt
          cargo install wasm-pack
          echo ${{ steps.version.outputs.tag }}
          ./ci/build-npm-packages.sh -v ${{ steps.version.outputs.tag }}
#            docker build -t wasm-ll --build-arg VER=0.0.0 -f Dockerfile.wasm .

